spring.datasource.url=jdbc:postgresql://localhost:5432/rapido_db
spring.datasource.username=postgres
spring.datasource.password=Nagesh2425
spring.datasource.driver-class-name=org.postgresql.Driver

dataset.riders=10000000
dataset.drivers=1000000
dataset.rides=100000000