spring.application.name=communication-service

server.port=8087

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/rapido_db
spring.datasource.username=postgres
spring.datasource.password=Nagesh2425
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ACTUATOR
management.endpoints.web.exposure.include=*

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379