server.port=8088

spring.application.name=search-service

# DB
spring.datasource.url=jdbc:postgresql://rapido-postgres:5432/rapido_db
spring.datasource.username=postgres
spring.datasource.password=Nagesh2425

# Kafka
spring.kafka.bootstrap-servers=rapido-kafka:9092

# Eureka
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

# Elasticsearch
spring.elasticsearch.uris=http://rapido-elasticsearch:9200

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.elasticsearch=INFO
logging.level.org.springframework.data.elasticsearch.client.WIRE=DEBUG

# Redis
spring.data.redis.host=rapido-redis
spring.data.redis.port=6379