server.port=8088

spring.application.name=admin-service

# PostgreSQL inside Kubernetes
spring.datasource.url=jdbc:postgresql://postgres:5432/rapido_db
spring.datasource.username=postgres
spring.datasource.password=Nagesh2425
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -----------------------------
# ✅ ACTUATOR (IMPORTANT FIX FOR K8s PROBES)
# -----------------------------
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

# -----------------------------
# OpenTelemetry
# -----------------------------
otel.service.name=admin-service
otel.exporter.otlp.endpoint=http://jaeger.observability.svc.cluster.local:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=parentbased_traceidratio
otel.traces.sampler.arg=1.0

# Trace correlation in logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} traceId=%X{trace_id} spanId=%X{span_id} %-5level %logger{36} - %msg%n