spring.application.name=performance-service

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.prometheus.access=unrestricted

management.metrics.tags.application=performance-service

management.metrics.distribution.percentiles-histogram.http.server.requests=true

management.metrics.distribution.percentiles.http.server.requests=0.95,0.99

# Compression
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/plain
server.compression.min-response-size=1024

# HTTP/2
server.http2.enabled=true

# Gateway Connection Pool
spring.cloud.gateway.httpclient.pool.type=elastic
spring.cloud.gateway.httpclient.pool.max-connections=1000

# Connection Timeout
spring.cloud.gateway.httpclient.connect-timeout=5000

spring.kafka.producer.batch-size=65536
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.compression-type=snappy
spring.kafka.producer.acks=all
spring.kafka.producer.linger-ms=10

spring.kafka.listener.concurrency=5
# Tomcat Thread Pool
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Async Executor
spring.task.execution.pool.core-size=20
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=500


server.tomcat.keep-alive-timeout=20000
server.tomcat.max-keep-alive-requests=100