--
-- PostgreSQL database dump
--

\restrict qvIzDYfHaVvov4tLu4kaIdWGIIe9f5dgHGa3nXUwltlm9fCaKliSKL7WmzqVzbw

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    action character varying(255),
    actor character varying(255),
    created_at timestamp(6) without time zone,
    event_type character varying(255)
);


ALTER TABLE public.audit_events OWNER TO postgres;

--
-- Name: audit_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255),
    user_name character varying(255),
    status character varying(255),
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.audit_logs_id_seq OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.audit_logs_id_seq OWNED BY public.audit_logs.id;


--
-- Name: cost_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cost_metrics (
    id bigint NOT NULL,
    environment_cost double precision,
    service_cost double precision,
    cluster_cost double precision,
    database_cost double precision,
    team_cost double precision
);


ALTER TABLE public.cost_metrics OWNER TO postgres;

--
-- Name: cost_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cost_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cost_metrics_id_seq OWNER TO postgres;

--
-- Name: cost_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cost_metrics_id_seq OWNED BY public.cost_metrics.id;


--
-- Name: deployment_audit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deployment_audit (
    id bigint NOT NULL,
    application_name character varying(255),
    environment character varying(255),
    action_type character varying(255),
    status character varying(255),
    created_at timestamp without time zone
);


ALTER TABLE public.deployment_audit OWNER TO postgres;

--
-- Name: deployment_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.deployment_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.deployment_audit_id_seq OWNER TO postgres;

--
-- Name: deployment_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.deployment_audit_id_seq OWNED BY public.deployment_audit.id;


--
-- Name: developer_onboarding; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.developer_onboarding (
    id bigint NOT NULL,
    developer_name character varying(255),
    email character varying(255),
    role_name character varying(255),
    access_granted boolean,
    environment_name character varying(255),
    status character varying(255)
);


ALTER TABLE public.developer_onboarding OWNER TO postgres;

--
-- Name: developer_onboarding_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.developer_onboarding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.developer_onboarding_id_seq OWNER TO postgres;

--
-- Name: developer_onboarding_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.developer_onboarding_id_seq OWNED BY public.developer_onboarding.id;


--
-- Name: documentation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documentation (
    id bigint NOT NULL,
    title character varying(255),
    category character varying(255),
    content text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.documentation OWNER TO postgres;

--
-- Name: documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.documentation_id_seq OWNER TO postgres;

--
-- Name: documentation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.documentation_id_seq OWNED BY public.documentation.id;


--
-- Name: dora_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dora_metrics (
    id bigint NOT NULL,
    deployments_per_day integer,
    lead_time_hours double precision,
    mttr_hours double precision,
    change_failure_rate double precision
);


ALTER TABLE public.dora_metrics OWNER TO postgres;

--
-- Name: dora_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dora_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dora_metrics_id_seq OWNER TO postgres;

--
-- Name: dora_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.dora_metrics_id_seq OWNED BY public.dora_metrics.id;


--
-- Name: environment_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.environment_info (
    id bigint NOT NULL,
    environment_name character varying(255),
    owner character varying(255),
    cpu_usage character varying(255),
    memory_usage character varying(255),
    deployment_status character varying(255)
);


ALTER TABLE public.environment_info OWNER TO postgres;

--
-- Name: environment_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.environment_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.environment_info_id_seq OWNER TO postgres;

--
-- Name: environment_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.environment_info_id_seq OWNED BY public.environment_info.id;


--
-- Name: environments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.environments (
    id bigint NOT NULL,
    environment_name character varying(255),
    owner character varying(255),
    status character varying(255),
    cluster_name character varying(255),
    namespace character varying(255)
);


ALTER TABLE public.environments OWNER TO postgres;

--
-- Name: environments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.environments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.environments_id_seq OWNER TO postgres;

--
-- Name: environments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.environments_id_seq OWNED BY public.environments.id;


--
-- Name: infrastructure_provision; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.infrastructure_provision (
    id bigint NOT NULL,
    environment character varying(255),
    service_name character varying(255),
    status character varying(255)
);


ALTER TABLE public.infrastructure_provision OWNER TO postgres;

--
-- Name: infrastructure_provision_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.infrastructure_provision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.infrastructure_provision_id_seq OWNER TO postgres;

--
-- Name: infrastructure_provision_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.infrastructure_provision_id_seq OWNED BY public.infrastructure_provision.id;


--
-- Name: platform_services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.platform_services (
    id bigint NOT NULL,
    service_name character varying(255),
    owner character varying(255),
    repository_url character varying(255),
    environment character varying(255),
    sla character varying(255)
);


ALTER TABLE public.platform_services OWNER TO postgres;

--
-- Name: platform_services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.platform_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.platform_services_id_seq OWNER TO postgres;

--
-- Name: platform_services_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.platform_services_id_seq OWNED BY public.platform_services.id;


--
-- Name: portal_modules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_modules (
    id bigint NOT NULL,
    description character varying(255),
    module_name character varying(255),
    status character varying(255)
);


ALTER TABLE public.portal_modules OWNER TO postgres;

--
-- Name: portal_modules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_catalog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_catalog (
    id bigint NOT NULL,
    service_name character varying(255),
    owner character varying(255),
    repository_url character varying(255),
    environment character varying(255),
    sla character varying(255)
);


ALTER TABLE public.service_catalog OWNER TO postgres;

--
-- Name: service_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.service_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.service_catalog_id_seq OWNER TO postgres;

--
-- Name: service_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.service_catalog_id_seq OWNED BY public.service_catalog.id;


--
-- Name: audit_logs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs ALTER COLUMN id SET DEFAULT nextval('public.audit_logs_id_seq'::regclass);


--
-- Name: cost_metrics id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cost_metrics ALTER COLUMN id SET DEFAULT nextval('public.cost_metrics_id_seq'::regclass);


--
-- Name: deployment_audit id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deployment_audit ALTER COLUMN id SET DEFAULT nextval('public.deployment_audit_id_seq'::regclass);


--
-- Name: developer_onboarding id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.developer_onboarding ALTER COLUMN id SET DEFAULT nextval('public.developer_onboarding_id_seq'::regclass);


--
-- Name: documentation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentation ALTER COLUMN id SET DEFAULT nextval('public.documentation_id_seq'::regclass);


--
-- Name: dora_metrics id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dora_metrics ALTER COLUMN id SET DEFAULT nextval('public.dora_metrics_id_seq'::regclass);


--
-- Name: environment_info id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment_info ALTER COLUMN id SET DEFAULT nextval('public.environment_info_id_seq'::regclass);


--
-- Name: environments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environments ALTER COLUMN id SET DEFAULT nextval('public.environments_id_seq'::regclass);


--
-- Name: infrastructure_provision id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.infrastructure_provision ALTER COLUMN id SET DEFAULT nextval('public.infrastructure_provision_id_seq'::regclass);


--
-- Name: platform_services id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.platform_services ALTER COLUMN id SET DEFAULT nextval('public.platform_services_id_seq'::regclass);


--
-- Name: service_catalog id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_catalog ALTER COLUMN id SET DEFAULT nextval('public.service_catalog_id_seq'::regclass);


--
-- Data for Name: audit_events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_events (id, action, actor, created_at, event_type) FROM stdin;
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, user_name, status, "timestamp") FROM stdin;
1	Deployment Started	platform-admin	SUCCESS	2026-06-18 11:44:45.856384
2	Deployment Completed	platform-admin	SUCCESS	2026-06-18 11:44:47.191001
3	Rollback Executed	platform-admin	SUCCESS	2026-06-18 11:44:47.205207
4	Infrastructure Created	platform-admin	SUCCESS	2026-06-18 11:44:49.12517
\.


--
-- Data for Name: cost_metrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cost_metrics (id, environment_cost, service_cost, cluster_cost, database_cost, team_cost) FROM stdin;
1	1500	800	2500	1200	3000
\.


--
-- Data for Name: deployment_audit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deployment_audit (id, application_name, environment, action_type, status, created_at) FROM stdin;
1	ride-service	dev	DEPLOY	SUCCESS	2026-06-17 23:48:29.701086
2	ride-service	N/A	ROLLBACK	SUCCESS	2026-06-17 23:48:37.906147
\.


--
-- Data for Name: developer_onboarding; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.developer_onboarding (id, developer_name, email, role_name, access_granted, environment_name, status) FROM stdin;
1	Sravika	sravika@test.com	Developer	t	dev-environment	COMPLETED
\.


--
-- Data for Name: documentation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documentation (id, title, category, content, created_at) FROM stdin;
1	Deployment Runbook	RUNBOOK	Steps to deploy applications	2026-06-18 11:26:27.94841
2	Service Catalog API	API_DOC	API documentation for service catalog	2026-06-18 11:26:28.056601
3	Platform Architecture	ARCHITECTURE	Architecture diagrams and flow	2026-06-18 11:26:28.098806
4	Developer Onboarding	ONBOARDING	Developer setup instructions	2026-06-18 11:26:29.554956
\.


--
-- Data for Name: dora_metrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dora_metrics (id, deployments_per_day, lead_time_hours, mttr_hours, change_failure_rate) FROM stdin;
1	25	2.5	1.2	4
\.


--
-- Data for Name: environment_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.environment_info (id, environment_name, owner, cpu_usage, memory_usage, deployment_status) FROM stdin;
1	DEV	platform-team	40%	60%	HEALTHY
\.


--
-- Data for Name: environments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.environments (id, environment_name, owner, status, cluster_name, namespace) FROM stdin;
1	development	platform-team	ACTIVE	dev-cluster	dev
2	qa	platform-team	ACTIVE	qa-cluster	qa
3	staging	platform-team	ACTIVE	staging-cluster	staging
4	production	platform-team	ACTIVE	prod-cluster	prod
\.


--
-- Data for Name: infrastructure_provision; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.infrastructure_provision (id, environment, service_name, status) FROM stdin;
1	staging	ride-service	PROVISIONED
2	prod	payment-service	PROVISIONED
\.


--
-- Data for Name: platform_services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.platform_services (id, service_name, owner, repository_url, environment, sla) FROM stdin;
1	ride-service	mobility-team	https://github.com/company/ride-service	prod	99.9%
\.


--
-- Data for Name: portal_modules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_modules (id, description, module_name, status) FROM stdin;
1	Platform Overview	Dashboard	ACTIVE
2	Service Registry	Service Catalog	ACTIVE
3	Deployment Management	Deployments	ACTIVE
4	Environment Management	Environments	ACTIVE
5	Prometheus Grafana Integration	Monitoring	ACTIVE
6	Developer Documentation	Documentation	ACTIVE
\.


--
-- Data for Name: service_catalog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_catalog (id, service_name, owner, repository_url, environment, sla) FROM stdin;
1	ride-service	mobility-team	https://github.com/company/ride-service	prod	99.9%
2	payment-service	payments-team	https://github.com/company/payment-service	prod	99.95%
3	ride-service	mobility-team	https://github.com/company/ride-service	prod	99.9%
4	payment-service	payments-team	https://github.com/company/payment-service	prod	99.95%
5	notification-service	communication-team	https://github.com/company/notification-service	prod	99.9%
6	user-service	identity-team	https://github.com/company/user-service	prod	99.99%
7	analytics-service	data-team	https://github.com/company/analytics-service	prod	99.9%
\.


--
-- Name: audit_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_events_id_seq', 1, false);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 4, true);


--
-- Name: cost_metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cost_metrics_id_seq', 1, true);


--
-- Name: deployment_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deployment_audit_id_seq', 2, true);


--
-- Name: developer_onboarding_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.developer_onboarding_id_seq', 1, true);


--
-- Name: documentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documentation_id_seq', 4, true);


--
-- Name: dora_metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dora_metrics_id_seq', 1, true);


--
-- Name: environment_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.environment_info_id_seq', 1, true);


--
-- Name: environments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.environments_id_seq', 4, true);


--
-- Name: infrastructure_provision_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.infrastructure_provision_id_seq', 2, true);


--
-- Name: platform_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.platform_services_id_seq', 1, true);


--
-- Name: portal_modules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_modules_id_seq', 6, true);


--
-- Name: service_catalog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_catalog_id_seq', 7, true);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: cost_metrics cost_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cost_metrics
    ADD CONSTRAINT cost_metrics_pkey PRIMARY KEY (id);


--
-- Name: deployment_audit deployment_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deployment_audit
    ADD CONSTRAINT deployment_audit_pkey PRIMARY KEY (id);


--
-- Name: developer_onboarding developer_onboarding_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.developer_onboarding
    ADD CONSTRAINT developer_onboarding_pkey PRIMARY KEY (id);


--
-- Name: documentation documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentation
    ADD CONSTRAINT documentation_pkey PRIMARY KEY (id);


--
-- Name: dora_metrics dora_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dora_metrics
    ADD CONSTRAINT dora_metrics_pkey PRIMARY KEY (id);


--
-- Name: environment_info environment_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment_info
    ADD CONSTRAINT environment_info_pkey PRIMARY KEY (id);


--
-- Name: environments environments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environments
    ADD CONSTRAINT environments_pkey PRIMARY KEY (id);


--
-- Name: infrastructure_provision infrastructure_provision_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.infrastructure_provision
    ADD CONSTRAINT infrastructure_provision_pkey PRIMARY KEY (id);


--
-- Name: platform_services platform_services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.platform_services
    ADD CONSTRAINT platform_services_pkey PRIMARY KEY (id);


--
-- Name: portal_modules portal_modules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_modules
    ADD CONSTRAINT portal_modules_pkey PRIMARY KEY (id);


--
-- Name: service_catalog service_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_catalog
    ADD CONSTRAINT service_catalog_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict qvIzDYfHaVvov4tLu4kaIdWGIIe9f5dgHGa3nXUwltlm9fCaKliSKL7WmzqVzbw

