sonar.projectKey=rapido-platform

sonar.projectName=Rapido Platform

sonar.sourceEncoding=UTF-8

sonar.java.source=17

sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml