--
-- PostgreSQL database dump
--

\restrict L8lm4nyWRNiDKkbv9g0H77I6MgKTChufw4qUpOFcDgJtrGIc3WxVhegiTthZKbO

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: rapido_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO rapido_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_users (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


ALTER TABLE public.admin_users OWNER TO postgres;

--
-- Name: admin_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    id bigint NOT NULL,
    active boolean,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    CONSTRAINT admins_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'OPERATIONS_ADMIN'::character varying, 'SUPPORT_ADMIN'::character varying, 'FINANCE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alerts (
    id bigint NOT NULL,
    alert_type character varying(255),
    message character varying(255),
    created_at timestamp without time zone
);


ALTER TABLE public.alerts OWNER TO postgres;

--
-- Name: alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.alerts_id_seq OWNER TO postgres;

--
-- Name: alerts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.alerts_id_seq OWNED BY public.alerts.id;


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(255),
    admin_email character varying(255),
    description character varying(255),
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.audit_log OWNER TO postgres;

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branding_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branding_configuration (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    company_name character varying(255),
    logo_url character varying(255),
    primary_color character varying(255)
);


ALTER TABLE public.branding_configuration OWNER TO postgres;

--
-- Name: branding_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.branding_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branding_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: call_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.call_sessions (
    id bigint NOT NULL,
    caller_id bigint,
    ended_at timestamp(6) without time zone,
    receiver_id bigint,
    ride_id bigint,
    started_at timestamp(6) without time zone,
    status character varying(255)
);


ALTER TABLE public.call_sessions OWNER TO postgres;

--
-- Name: call_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.call_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.call_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    delivered boolean,
    message character varying(1000),
    read boolean,
    receiver_id bigint,
    ride_id bigint,
    sender_id bigint,
    sent_at timestamp(6) without time zone
);


ALTER TABLE public.chat_messages OWNER TO postgres;

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    active boolean NOT NULL,
    city_code character varying(255) NOT NULL,
    city_name character varying(255) NOT NULL,
    region_id bigint NOT NULL
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compliance_configurations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compliance_configurations (
    id bigint NOT NULL,
    country_code character varying(10) NOT NULL,
    data_retention_days integer NOT NULL,
    privacy_policy_version character varying(255) NOT NULL,
    document_requirement character varying(255) NOT NULL,
    ride_history_retention_days integer NOT NULL
);


ALTER TABLE public.compliance_configurations OWNER TO postgres;

--
-- Name: compliance_configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.compliance_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.compliance_configurations_id_seq OWNER TO postgres;

--
-- Name: compliance_configurations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.compliance_configurations_id_seq OWNED BY public.compliance_configurations.id;


--
-- Name: consent_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consent_logs (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL
);


ALTER TABLE public.consent_logs OWNER TO postgres;

--
-- Name: consent_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.consent_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.consent_logs_id_seq OWNER TO postgres;

--
-- Name: consent_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.consent_logs_id_seq OWNED BY public.consent_logs.id;


--
-- Name: countries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.countries (
    id bigint NOT NULL,
    active boolean NOT NULL,
    country_code character varying(10) NOT NULL,
    country_name character varying(100) NOT NULL,
    default_currency character varying(10) NOT NULL,
    default_language character varying(20) NOT NULL,
    time_zone character varying(100) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.countries OWNER TO postgres;

--
-- Name: countries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country_business_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country_business_rules (
    id bigint NOT NULL,
    country_code character varying(10) NOT NULL,
    vehicle_type character varying(50) NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.country_business_rules OWNER TO postgres;

--
-- Name: country_business_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.country_business_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.country_business_rules_id_seq OWNER TO postgres;

--
-- Name: country_business_rules_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.country_business_rules_id_seq OWNED BY public.country_business_rules.id;


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currencies (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(10) NOT NULL,
    decimal_places integer NOT NULL,
    symbol character varying(10) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.currencies OWNER TO postgres;

--
-- Name: currencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_earnings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_earnings (
    id bigint NOT NULL,
    driver_id bigint NOT NULL,
    total_earnings double precision
);


ALTER TABLE public.driver_earnings OWNER TO postgres;

--
-- Name: driver_earnings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver_earnings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_earnings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_location_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_location_history (
    id bigint NOT NULL,
    distance_km double precision,
    driver_id bigint,
    eta_minutes double precision,
    latitude double precision,
    longitude double precision,
    ride_id bigint,
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.driver_location_history OWNER TO postgres;

--
-- Name: driver_location_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver_location_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_location_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_performance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_performance (
    driver_id bigint NOT NULL,
    acceptance_rate double precision,
    average_rating double precision,
    cancelled_rides integer,
    completed_rides integer,
    earnings double precision,
    performance_score double precision
);


ALTER TABLE public.driver_performance OWNER TO postgres;

--
-- Name: drivers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    acceptance_rate double precision,
    active boolean,
    available boolean,
    cancellation_rate double precision,
    current_load integer,
    latitude double precision,
    longitude double precision,
    name character varying(255),
    phone_number character varying(255),
    rating double precision,
    vehicle_number character varying(255)
);


ALTER TABLE public.drivers OWNER TO postgres;

--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchange_rates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exchange_rates (
    id bigint NOT NULL,
    base_currency character varying(255) NOT NULL,
    rate numeric(19,6) NOT NULL,
    rate_date date NOT NULL,
    target_currency character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.exchange_rates OWNER TO postgres;

--
-- Name: exchange_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_flags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feature_flags (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    chat_enabled boolean,
    fraud_detection_enabled boolean,
    ml_forecast_enabled boolean,
    wallet_enabled boolean,
    region_code character varying(255),
    country_code character varying(255),
    feature_name character varying(255),
    enabled boolean
);


ALTER TABLE public.feature_flags OWNER TO postgres;

--
-- Name: feature_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feature_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_store; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feature_store (
    id bigint NOT NULL,
    active_drivers integer,
    active_riders integer,
    cancellation_rate double precision,
    city character varying(255),
    created_at timestamp(6) without time zone,
    day_of_week integer,
    hour_of_day integer,
    revenue numeric(38,2),
    ride_count integer,
    weather character varying(255),
    fraud_flag boolean DEFAULT false,
    spam_request_flag boolean DEFAULT false,
    fake_driver_flag boolean DEFAULT false
);


ALTER TABLE public.feature_store OWNER TO postgres;

--
-- Name: feature_store_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feature_store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fraud_alert; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fraud_alert (
    id bigint NOT NULL,
    description character varying(255),
    fraud_type character varying(255),
    resolved boolean,
    severity character varying(255),
    user_id bigint
);


ALTER TABLE public.fraud_alert OWNER TO postgres;

--
-- Name: fraud_alert_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fraud_alert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fraud_alert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: international_analytics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.international_analytics (
    id bigint NOT NULL,
    country_code character varying(255) NOT NULL,
    currency_code character varying(255) NOT NULL,
    region_code character varying(255) NOT NULL,
    total_revenue numeric(19,2) NOT NULL,
    total_rides bigint NOT NULL,
    growth_percentage numeric(10,2),
    analytics_date timestamp without time zone
);


ALTER TABLE public.international_analytics OWNER TO postgres;

--
-- Name: international_analytics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.international_analytics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.international_analytics_id_seq OWNER TO postgres;

--
-- Name: international_analytics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.international_analytics_id_seq OWNED BY public.international_analytics.id;


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    country_code character varying(255),
    currency_code character varying(255),
    customer_name character varying(255),
    fare_amount numeric(19,2),
    ride_id character varying(255),
    tax_amount numeric(19,2),
    total_amount numeric(19,2),
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model_audit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_audit (
    id bigint NOT NULL,
    action character varying(255),
    model_version character varying(255),
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.model_audit OWNER TO postgres;

--
-- Name: model_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.model_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model_registry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_registry (
    id bigint NOT NULL,
    model_name character varying(255),
    model_version character varying(255),
    algorithm character varying(255),
    mae double precision,
    rmse double precision,
    r2 double precision,
    model_path character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    active boolean
);


ALTER TABLE public.model_registry OWNER TO postgres;

--
-- Name: model_registry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.model_registry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.model_registry_id_seq OWNER TO postgres;

--
-- Name: model_registry_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.model_registry_id_seq OWNED BY public.model_registry.id;


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(255),
    recipient character varying(255),
    retry_count integer,
    status character varying(255),
    title character varying(255),
    type character varying(255),
    user_id bigint,
    CONSTRAINT notifications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying, 'RETRYING'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['PUSH'::character varying, 'SMS'::character varying, 'EMAIL'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations (
    id bigint NOT NULL,
    active boolean,
    organization_code character varying(255) NOT NULL,
    organization_name character varying(255) NOT NULL,
    subscription_plan character varying(255),
    tenant_id character varying(255) NOT NULL
);


ALTER TABLE public.organizations OWNER TO postgres;

--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_gateway_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_gateway_config (
    id bigint NOT NULL,
    country_code character varying(10) NOT NULL,
    gateway_name character varying(100) NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.payment_gateway_config OWNER TO postgres;

--
-- Name: payment_gateway_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.payment_gateway_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payment_gateway_config_id_seq OWNER TO postgres;

--
-- Name: payment_gateway_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.payment_gateway_config_id_seq OWNED BY public.payment_gateway_config.id;


--
-- Name: prediction_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prediction_metrics (
    id bigint NOT NULL,
    average_prediction double precision,
    last_prediction_time timestamp(6) without time zone,
    max_prediction double precision,
    min_prediction double precision,
    prediction_count bigint
);


ALTER TABLE public.prediction_metrics OWNER TO postgres;

--
-- Name: prediction_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prediction_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prediction_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pricing_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pricing_rules (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    base_fare numeric(19,2),
    commission_percentage double precision,
    surge_multiplier double precision,
    city_adjustment numeric(19,2),
    peak_surge_multiplier numeric(10,2),
    tax_percentage numeric(10,2),
    country_code character varying(255),
    city_code character varying(255),
    vehicle_type character varying(255)
);


ALTER TABLE public.pricing_rules OWNER TO postgres;

--
-- Name: pricing_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pricing_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pricing_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.regions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    region_code character varying(255) NOT NULL,
    region_name character varying(255) NOT NULL,
    country_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.regions OWNER TO postgres;

--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ride_policies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride_policies (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    active boolean,
    base_fare double precision,
    cancellation_fee double precision,
    max_distance double precision,
    ride_type character varying(255)
);


ALTER TABLE public.ride_policies OWNER TO postgres;

--
-- Name: ride_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ride_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ride_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride_status_history (
    id bigint NOT NULL,
    message character varying(255),
    ride_id bigint,
    status character varying(255),
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.ride_status_history OWNER TO postgres;

--
-- Name: ride_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ride_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rides; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rides (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    driver_id bigint,
    drop_latitude double precision,
    drop_longitude double precision,
    estimated_distance double precision,
    estimated_fare double precision,
    pickup_latitude double precision,
    pickup_longitude double precision,
    requested_at timestamp(6) without time zone,
    status character varying(255),
    user_id bigint,
    fare numeric(19,2) DEFAULT 0 NOT NULL,
    tax numeric(19,2) DEFAULT 0 NOT NULL,
    total_amount numeric(19,2) DEFAULT 0 NOT NULL,
    CONSTRAINT rides_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'ACCEPTED'::character varying, 'STARTED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.rides OWNER TO postgres;

--
-- Name: rides_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    role_name character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_zones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_zones (
    id bigint NOT NULL,
    active boolean NOT NULL,
    operating_hours character varying(255),
    pricing_rule character varying(255),
    supported_ride_types character varying(255),
    zone_code character varying(255) NOT NULL,
    zone_name character varying(255) NOT NULL,
    city_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.service_zones OWNER TO postgres;

--
-- Name: service_zones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_zones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription_plans (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    analytics_access boolean,
    driver_limit integer,
    ml_features boolean,
    plan_name character varying(255),
    ride_limit integer
);


ALTER TABLE public.subscription_plans OWNER TO postgres;

--
-- Name: subscription_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tax_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tax_rules (
    id bigint NOT NULL,
    country_code character varying(10) NOT NULL,
    percentage numeric(10,2) NOT NULL,
    tax_type character varying(50) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.tax_rules OWNER TO postgres;

--
-- Name: tax_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tax_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_alerts (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    alert_message character varying(255),
    alert_type character varying(255),
    severity character varying(255),
    status character varying(255)
);


ALTER TABLE public.tenant_alerts OWNER TO postgres;

--
-- Name: tenant_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_audit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_audit (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    action_details character varying(255),
    action_type character varying(255),
    created_at timestamp(6) without time zone,
    performed_by character varying(255)
);


ALTER TABLE public.tenant_audit OWNER TO postgres;

--
-- Name: tenant_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_billing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_billing (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    monthly_charge double precision,
    plan character varying(255),
    feature_charge double precision,
    total_charge double precision,
    usage_charge double precision
);


ALTER TABLE public.tenant_billing OWNER TO postgres;

--
-- Name: tenant_billing_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_billing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_billing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_compliance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_compliance (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    compliance_status character varying(255),
    compliance_type character varying(255),
    remarks character varying(255)
);


ALTER TABLE public.tenant_compliance OWNER TO postgres;

--
-- Name: tenant_compliance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_compliance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_compliance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_configuration (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    commission_rule character varying(255),
    pricing_rule character varying(255),
    ride_category character varying(255),
    notification_template character varying(255)
);


ALTER TABLE public.tenant_configuration OWNER TO postgres;

--
-- Name: tenant_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_health; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_health (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    api_status character varying(255),
    billing_status character varying(255),
    database_status character varying(255),
    notification_status character varying(255)
);


ALTER TABLE public.tenant_health OWNER TO postgres;

--
-- Name: tenant_health_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_health ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_health_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_notifications (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    message character varying(255),
    notification_type character varying(255),
    recipient character varying(255),
    status character varying(255)
);


ALTER TABLE public.tenant_notifications OWNER TO postgres;

--
-- Name: tenant_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_sla; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_sla (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    sla_type character varying(255),
    status character varying(255),
    target_value character varying(255)
);


ALTER TABLE public.tenant_sla OWNER TO postgres;

--
-- Name: tenant_sla_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_sla ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_sla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    organization_id bigint NOT NULL,
    status character varying(255),
    tenant_code character varying(255) NOT NULL,
    tenant_id character varying(255) NOT NULL
);


ALTER TABLE public.tenants OWNER TO postgres;

--
-- Name: tenants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount double precision,
    created_at timestamp(6) without time zone,
    driver_id bigint,
    payer_id bigint,
    ride_id bigint,
    status character varying(255),
    transaction_reference character varying(255),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usage_tracking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usage_tracking (
    id bigint NOT NULL,
    tenant_id character varying(255) NOT NULL,
    api_calls bigint,
    drivers bigint,
    rides bigint,
    storage_usage_mb bigint
);


ALTER TABLE public.usage_tracking OWNER TO postgres;

--
-- Name: usage_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usage_tracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usage_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_deletion_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_deletion_requests (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL
);


ALTER TABLE public.user_deletion_requests OWNER TO postgres;

--
-- Name: user_deletion_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_deletion_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_deletion_requests_id_seq OWNER TO postgres;

--
-- Name: user_deletion_requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_deletion_requests_id_seq OWNED BY public.user_deletion_requests.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: rapido_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    password character varying(255),
    role character varying(255),
    active boolean,
    phone character varying(255),
    profile_image character varying(255),
    name character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    phone_number character varying(30),
    phone_number_e164 character varying(30)
);


ALTER TABLE public.users OWNER TO rapido_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: rapido_user
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO rapido_user;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rapido_user
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    active boolean NOT NULL,
    balance double precision NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wallets OWNER TO postgres;

--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alerts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerts ALTER COLUMN id SET DEFAULT nextval('public.alerts_id_seq'::regclass);


--
-- Name: compliance_configurations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_configurations ALTER COLUMN id SET DEFAULT nextval('public.compliance_configurations_id_seq'::regclass);


--
-- Name: consent_logs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_logs ALTER COLUMN id SET DEFAULT nextval('public.consent_logs_id_seq'::regclass);


--
-- Name: country_business_rules id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country_business_rules ALTER COLUMN id SET DEFAULT nextval('public.country_business_rules_id_seq'::regclass);


--
-- Name: international_analytics id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.international_analytics ALTER COLUMN id SET DEFAULT nextval('public.international_analytics_id_seq'::regclass);


--
-- Name: model_registry id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_registry ALTER COLUMN id SET DEFAULT nextval('public.model_registry_id_seq'::regclass);


--
-- Name: payment_gateway_config id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_gateway_config ALTER COLUMN id SET DEFAULT nextval('public.payment_gateway_config_id_seq'::regclass);


--
-- Name: user_deletion_requests id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_deletion_requests ALTER COLUMN id SET DEFAULT nextval('public.user_deletion_requests_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: rapido_user
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: admin_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_users (id, tenant_id, email, password, role, username) FROM stdin;
1	TENANT_100	admin@rapido.com	admin123	ADMIN	admin
\.


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (id, active, email, name, password, role) FROM stdin;
3	t	admin@rapido.com	Super Admin	$2a$10$Mk4Lq7QCj1SBYczu7mITr.zF5LiwFvkWHgGLCBr7ik4AdLtpgZzUW	SUPER_ADMIN
\.


--
-- Data for Name: alerts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alerts (id, alert_type, message, created_at) FROM stdin;
1	DATA_DRIFT	Drift threshold exceeded	2026-06-11 20:37:16.734415
\.


--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_log (id, action, admin_email, description, "timestamp") FROM stdin;
1	DRIVER_SUSPENSION	admin@rapido.com	Driver 101 suspended	2026-05-30 12:35:26.968653
2	USER_BAN	admin@rapido.com	User 501 banned. Type: TEMPORARY, Reason: FakeRideActivity	2026-05-30 12:45:04.017364
3	DRIVER_SUSPENSION	admin@rapido.com	Driver 101 suspended	2026-05-30 13:51:25.393555
4	USER_BAN	admin@rapido.com	User 501 banned. Type: TEMPORARY, Reason: FakeRideActivity	2026-05-30 13:56:57.211687
\.


--
-- Data for Name: branding_configuration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.branding_configuration (id, tenant_id, company_name, logo_url, primary_color) FROM stdin;
1	TENANT_100	Rapido Chennai Premium	https://rapido.com/new-logo.png	#0000FF
\.


--
-- Data for Name: call_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.call_sessions (id, caller_id, ended_at, receiver_id, ride_id, started_at, status) FROM stdin;
1	101	\N	202	1	2026-05-28 00:18:39.194027	INITIATED
\.


--
-- Data for Name: chat_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_messages (id, delivered, message, read, receiver_id, ride_id, sender_id, sent_at) FROM stdin;
1	t	Hello Driver	t	202	1	101	2026-05-28 00:02:49.978654
2	t	Hello Driver	t	202	1	101	2026-05-28 00:12:35.111906
3	t	Hello Driver	t	202	1	101	2026-05-28 00:15:57.424084
4	t	Hello Driver	t	202	1	101	2026-05-28 00:18:28.530765
5	t	Authorized User	f	202	1	101	2026-05-28 01:38:52.917754
10	t	Redis Test Message	f	202	1	101	2026-05-28 10:14:06.27413
11	t	Redis Test Message	f	202	1	101	2026-05-28 10:26:59.963603
12	t	Redis Test Message	f	202	1	101	2026-05-28 11:23:17.647883
\.


--
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cities (id, active, city_code, city_name, region_id) FROM stdin;
1	t	BLR	Bangalore	1
\.


--
-- Data for Name: compliance_configurations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compliance_configurations (id, country_code, data_retention_days, privacy_policy_version, document_requirement, ride_history_retention_days) FROM stdin;
1	IN	2555	INDIA_PRIVACY_V1	AADHAR,PAN	2555
2	EU	730	GDPR_V1	PASSPORT	730
3	AE	1825	UAE_PRIVACY_V1	EMIRATES_ID	1825
\.


--
-- Data for Name: consent_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.consent_logs (id, user_id, action, created_at) FROM stdin;
1	100	DATA_EXPORT	2026-06-13 10:27:18.89922
2	100	ACCOUNT_DELETION_REQUEST	2026-06-13 10:27:34.0591
\.


--
-- Data for Name: countries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.countries (id, active, country_code, country_name, default_currency, default_language, time_zone, created_at, updated_at) FROM stdin;
1	t	IN	India	INR	en	Asia/Kolkata	2026-06-13 14:54:39.111358	2026-06-13 14:54:39.111358
2	t	US	United States	USD	en	America/New_York	2026-06-13 14:54:39.111358	2026-06-13 14:54:39.111358
3	t	AE	United Arab Emirates	AED	ar	Asia/Dubai	2026-06-13 14:54:39.111358	2026-06-13 14:54:39.111358
4	t	GB	United Kingdom	GBP	en	Europe/London	2026-06-13 14:54:39.111358	2026-06-13 14:54:39.111358
\.


--
-- Data for Name: country_business_rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.country_business_rules (id, country_code, vehicle_type, active) FROM stdin;
1	IN	BIKE	t
2	IN	AUTO	t
3	IN	CAB	t
4	EU	TAXI	t
5	EU	ELECTRIC_VEHICLE	t
6	AE	PREMIUM_VEHICLE	t
\.


--
-- Data for Name: currencies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.currencies (id, active, code, decimal_places, symbol, created_at, updated_at) FROM stdin;
1	t	INR	2	?	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
2	t	USD	2	$	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
3	t	AED	2	AED	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
4	t	GBP	2	œ	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
5	t	EUR	2	?	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
6	t	JPY	0	¥	2026-06-13 14:54:39.169731	2026-06-13 14:54:39.169731
\.


--
-- Data for Name: driver_earnings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.driver_earnings (id, driver_id, total_earnings) FROM stdin;
1	101	0
\.


--
-- Data for Name: driver_location_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.driver_location_history (id, distance_km, driver_id, eta_minutes, latitude, longitude, ride_id, "timestamp") FROM stdin;
1	\N	501	\N	17.4401	78.3489	101	2026-05-13 22:08:05.83842
\.


--
-- Data for Name: driver_performance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.driver_performance (driver_id, acceptance_rate, average_rating, cancelled_rides, completed_rides, earnings, performance_score) FROM stdin;
\.


--
-- Data for Name: drivers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drivers (id, acceptance_rate, active, available, cancellation_rate, current_load, latitude, longitude, name, phone_number, rating, vehicle_number) FROM stdin;
1	90	t	f	5	1	17.385	78.4867	Driver One	9876543210	4.5	TS09AB1234
2	88	t	f	6	1	17.395	78.4967	Driver Two	9876543211	4.3	TS09AB5678
3	92	t	f	4	1	17.405	78.5067	Driver Three	9876543212	4.7	TS09AB9999
\.


--
-- Data for Name: exchange_rates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exchange_rates (id, base_currency, rate, rate_date, target_currency, created_at, updated_at) FROM stdin;
1	USD	86.250000	2026-06-13	INR	2026-06-13 14:54:39.17921	2026-06-13 14:54:39.17921
2	USD	3.670000	2026-06-13	AED	2026-06-13 14:54:39.17921	2026-06-13 14:54:39.17921
3	USD	0.740000	2026-06-13	GBP	2026-06-13 14:54:39.17921	2026-06-13 14:54:39.17921
4	USD	86.250000	2026-06-14	INR	\N	\N
5	USD	3.670000	2026-06-14	AED	\N	\N
6	USD	0.740000	2026-06-14	GBP	\N	\N
\.


--
-- Data for Name: feature_flags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.feature_flags (id, tenant_id, chat_enabled, fraud_detection_enabled, ml_forecast_enabled, wallet_enabled, region_code, country_code, feature_name, enabled) FROM stdin;
1	TENANT_100	t	t	t	f	\N	\N	\N	\N
2	TENANT_100	\N	\N	\N	\N	KA	IN	WALLET	t
3	TENANT_100	\N	\N	\N	\N	KA	IN	CASH_PAYMENT	t
4	TENANT_100	\N	\N	\N	\N	DXB	AE	CASH_PAYMENT	f
5	TENANT_100	\N	\N	\N	\N	BERLIN	EU	PROMOTIONS	f
\.


--
-- Data for Name: feature_store; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.feature_store (id, active_drivers, active_riders, cancellation_rate, city, created_at, day_of_week, hour_of_day, revenue, ride_count, weather, fraud_flag, spam_request_flag, fake_driver_flag) FROM stdin;
6	408	3264	0.17	Hyderabad	2026-06-11 12:45:30.217949	6	10	166116.00	2557	RAIN	f	f	f
7	811	3683	0.04	Hyderabad	2026-06-11 12:45:30.217949	1	18	79675.00	5665	SUNNY	f	f	f
8	904	1171	0.16	Hyderabad	2026-06-11 12:45:30.217949	6	5	337298.00	5418	SUNNY	f	f	f
9	748	4278	0.04	Hyderabad	2026-06-11 12:45:30.217949	6	20	328485.00	3488	RAIN	f	f	f
10	450	4090	0.15	Hyderabad	2026-06-11 12:45:30.217949	2	3	512552.00	1704	RAIN	f	f	f
11	280	2633	0.08	Hyderabad	2026-06-11 12:45:30.217949	5	2	390307.00	5549	SUNNY	f	f	f
12	260	5206	0.05	Hyderabad	2026-06-11 12:45:30.217949	1	9	458678.00	4357	RAIN	f	f	f
13	570	2391	0.16	Hyderabad	2026-06-11 12:45:30.217949	5	19	512466.00	5207	SUNNY	f	f	f
14	273	2061	0.02	Hyderabad	2026-06-11 12:45:30.217949	3	6	88474.00	3695	SUNNY	f	f	f
15	561	1154	0.04	Hyderabad	2026-06-11 12:45:30.217949	3	6	454591.00	2200	RAIN	f	f	f
16	457	3817	0.15	Hyderabad	2026-06-11 12:45:30.217949	4	5	512495.00	1668	SUNNY	f	f	f
17	518	917	0.15	Hyderabad	2026-06-11 12:45:30.217949	7	2	261009.00	1979	RAIN	f	f	f
18	982	3879	0.12	Hyderabad	2026-06-11 12:45:30.217949	2	23	420978.00	5833	SUNNY	f	f	f
19	1029	2112	0.09	Hyderabad	2026-06-11 12:45:30.217949	5	9	410181.00	4474	SUNNY	f	f	f
20	140	3654	0.18	Hyderabad	2026-06-11 12:45:30.217949	1	17	238503.00	1715	RAIN	f	f	f
21	130	2369	0.09	Hyderabad	2026-06-11 12:45:30.217949	3	18	321731.00	1368	RAIN	f	f	f
22	964	1328	0.09	Hyderabad	2026-06-11 12:45:30.217949	6	18	222315.00	3779	SUNNY	f	f	f
23	947	3818	0.12	Hyderabad	2026-06-11 12:45:30.217949	3	4	93456.00	3849	SUNNY	f	f	f
24	133	5432	0.04	Hyderabad	2026-06-11 12:45:30.217949	6	12	398211.00	4357	RAIN	f	f	f
25	401	4412	0.19	Hyderabad	2026-06-11 12:45:30.217949	6	21	431679.00	3839	SUNNY	f	f	f
26	286	4735	0.02	Hyderabad	2026-06-11 12:45:30.217949	4	19	218184.00	4629	RAIN	f	f	f
27	925	4286	0.02	Hyderabad	2026-06-11 12:45:30.217949	6	20	59133.00	3127	SUNNY	f	f	f
28	592	2661	0.09	Hyderabad	2026-06-11 12:45:30.217949	4	13	50095.00	2439	SUNNY	f	f	f
29	612	6013	0.19	Hyderabad	2026-06-11 12:45:30.217949	2	12	65361.00	2178	SUNNY	f	f	f
30	508	5178	0.18	Hyderabad	2026-06-11 12:45:30.217949	6	7	541928.00	4599	RAIN	f	f	f
31	760	2350	0.16	Hyderabad	2026-06-11 12:45:30.217949	6	2	301490.00	5258	SUNNY	f	f	f
32	876	5700	0.07	Hyderabad	2026-06-11 12:45:30.217949	6	9	137465.00	5597	SUNNY	f	f	f
33	156	4973	0.2	Hyderabad	2026-06-11 12:45:30.217949	2	20	167508.00	5110	RAIN	f	f	f
34	810	6377	0.01	Hyderabad	2026-06-11 12:45:30.217949	7	4	481595.00	3740	SUNNY	f	f	f
35	744	1188	0.13	Hyderabad	2026-06-11 12:45:30.217949	6	0	351601.00	1802	RAIN	f	f	f
36	348	687	0.13	Hyderabad	2026-06-11 12:45:30.217949	6	21	394747.00	3682	RAIN	f	f	f
37	1073	2168	0.08	Hyderabad	2026-06-11 12:45:30.217949	1	8	64612.00	4837	SUNNY	f	f	f
38	239	950	0.06	Hyderabad	2026-06-11 12:45:30.217949	7	18	299645.00	5387	SUNNY	f	f	f
39	1007	600	0.03	Hyderabad	2026-06-11 12:45:30.217949	2	6	167782.00	5082	RAIN	f	f	f
40	129	4625	0.06	Hyderabad	2026-06-11 12:45:30.217949	1	13	338146.00	4923	SUNNY	f	f	f
41	319	5030	0.1	Hyderabad	2026-06-11 12:45:30.217949	3	10	523821.00	1106	RAIN	f	f	f
42	606	2960	0.16	Hyderabad	2026-06-11 12:45:30.217949	4	12	238347.00	1472	RAIN	f	f	f
43	782	1390	0.07	Hyderabad	2026-06-11 12:45:30.217949	1	17	51627.00	1110	SUNNY	f	f	f
44	444	1252	0.07	Hyderabad	2026-06-11 12:45:30.217949	1	18	316341.00	2150	RAIN	f	f	f
45	860	4414	0.12	Hyderabad	2026-06-11 12:45:30.217949	7	10	465038.00	5967	SUNNY	f	f	f
46	922	6261	0.06	Hyderabad	2026-06-11 12:45:30.217949	6	5	457985.00	4464	RAIN	f	f	f
47	136	5754	0.06	Hyderabad	2026-06-11 12:45:30.217949	6	8	500490.00	1306	SUNNY	f	f	f
48	776	3969	0.09	Hyderabad	2026-06-11 12:45:30.217949	5	22	299734.00	3941	SUNNY	f	f	f
49	418	1238	0.16	Hyderabad	2026-06-11 12:45:30.217949	6	16	409721.00	3460	SUNNY	f	f	f
50	176	3522	0.17	Hyderabad	2026-06-11 12:45:30.217949	4	15	424977.00	3768	SUNNY	f	f	f
51	779	2289	0.15	Hyderabad	2026-06-11 12:45:30.217949	2	4	251695.00	3686	SUNNY	f	f	f
52	614	4907	0.13	Hyderabad	2026-06-11 12:45:30.217949	6	1	441953.00	2321	SUNNY	f	f	f
53	889	6403	0.01	Hyderabad	2026-06-11 12:45:30.217949	3	7	247882.00	1937	RAIN	f	f	f
54	685	3443	0.12	Hyderabad	2026-06-11 12:45:30.217949	3	10	307800.00	5882	SUNNY	f	f	f
55	602	2263	0.2	Hyderabad	2026-06-11 12:45:30.217949	1	13	118038.00	1550	SUNNY	f	f	f
56	514	1581	0.11	Hyderabad	2026-06-11 12:45:30.217949	2	15	408140.00	2934	SUNNY	f	f	f
57	994	3641	0.11	Hyderabad	2026-06-11 12:45:30.217949	7	8	333150.00	4928	SUNNY	f	f	f
58	331	6209	0.06	Hyderabad	2026-06-11 12:45:30.217949	3	19	519853.00	1249	SUNNY	f	f	f
59	1077	2409	0.06	Hyderabad	2026-06-11 12:45:30.217949	1	14	63053.00	4358	SUNNY	f	f	f
60	289	5363	0	Hyderabad	2026-06-11 12:45:30.217949	6	18	150194.00	2196	RAIN	f	f	f
61	1002	3635	0.14	Hyderabad	2026-06-11 12:45:30.217949	4	20	336525.00	4399	SUNNY	f	f	f
62	821	1206	0.01	Hyderabad	2026-06-11 12:45:30.217949	1	20	324917.00	5032	SUNNY	f	f	f
63	382	3737	0.15	Hyderabad	2026-06-11 12:45:30.217949	6	3	137609.00	1272	SUNNY	f	f	f
64	858	5304	0.04	Hyderabad	2026-06-11 12:45:30.217949	3	18	72461.00	3956	SUNNY	f	f	f
65	390	1438	0.08	Hyderabad	2026-06-11 12:45:30.217949	3	15	427188.00	3490	SUNNY	f	f	f
66	770	3121	0.12	Hyderabad	2026-06-11 12:45:30.217949	3	1	506878.00	4157	SUNNY	f	f	f
67	630	1889	0.01	Hyderabad	2026-06-11 12:45:30.217949	3	4	73954.00	4892	SUNNY	f	f	f
68	353	5756	0.11	Hyderabad	2026-06-11 12:45:30.217949	7	7	154715.00	4151	SUNNY	f	f	f
69	290	1993	0.08	Hyderabad	2026-06-11 12:45:30.217949	3	18	402722.00	5113	RAIN	f	f	f
70	916	5983	0.13	Hyderabad	2026-06-11 12:45:30.217949	6	3	117985.00	4248	SUNNY	f	f	f
71	912	4917	0.12	Hyderabad	2026-06-11 12:45:30.217949	1	22	116399.00	5750	RAIN	f	f	f
72	675	1080	0.14	Hyderabad	2026-06-11 12:45:30.217949	5	16	311987.00	5232	SUNNY	f	f	f
73	580	6105	0.2	Hyderabad	2026-06-11 12:45:30.217949	4	5	324518.00	5857	SUNNY	f	f	f
74	335	5264	0.04	Hyderabad	2026-06-11 12:45:30.217949	2	20	541523.00	2146	SUNNY	f	f	f
75	286	4648	0.04	Hyderabad	2026-06-11 12:45:30.217949	4	6	154273.00	3214	RAIN	f	f	f
76	951	4371	0.17	Hyderabad	2026-06-11 12:45:30.217949	1	13	205717.00	5181	SUNNY	f	f	f
77	337	5778	0.13	Hyderabad	2026-06-11 12:45:30.217949	6	22	476048.00	3166	SUNNY	f	f	f
78	1063	5323	0.01	Hyderabad	2026-06-11 12:45:30.217949	2	20	147250.00	2061	SUNNY	f	f	f
79	281	6067	0.06	Hyderabad	2026-06-11 12:45:30.217949	3	14	193551.00	1289	SUNNY	f	f	f
80	834	3607	0.14	Hyderabad	2026-06-11 12:45:30.217949	4	8	458191.00	1651	SUNNY	f	f	f
81	876	4332	0.15	Hyderabad	2026-06-11 12:45:30.217949	5	15	258086.00	2964	SUNNY	f	f	f
82	542	2863	0.14	Hyderabad	2026-06-11 12:45:30.217949	1	12	547078.00	2397	SUNNY	f	f	f
83	922	4121	0.09	Hyderabad	2026-06-11 12:45:30.217949	7	9	269094.00	5441	SUNNY	f	f	f
84	888	2248	0.03	Hyderabad	2026-06-11 12:45:30.217949	7	19	407245.00	1677	SUNNY	f	f	f
85	378	1456	0.19	Hyderabad	2026-06-11 12:45:30.217949	4	15	486589.00	3123	SUNNY	f	f	f
86	518	2354	0.14	Hyderabad	2026-06-11 12:45:30.217949	2	11	62632.00	4498	SUNNY	f	f	f
87	781	2572	0.01	Hyderabad	2026-06-11 12:45:30.217949	4	2	319483.00	4465	SUNNY	f	f	f
88	126	2305	0.14	Hyderabad	2026-06-11 12:45:30.217949	4	20	545132.00	5100	SUNNY	f	f	f
89	361	6026	0.17	Hyderabad	2026-06-11 12:45:30.217949	5	18	167725.00	2851	SUNNY	f	f	f
90	233	5560	0.13	Hyderabad	2026-06-11 12:45:30.217949	4	5	192784.00	4212	SUNNY	f	f	f
91	174	2118	0.16	Hyderabad	2026-06-11 12:45:30.217949	5	4	463776.00	1687	SUNNY	f	f	f
92	282	1579	0.13	Hyderabad	2026-06-11 12:45:30.217949	4	6	197378.00	3218	SUNNY	f	f	f
93	386	5505	0.18	Hyderabad	2026-06-11 12:45:30.217949	7	13	490200.00	4612	SUNNY	f	f	f
94	228	3404	0.01	Hyderabad	2026-06-11 12:45:30.217949	3	19	271512.00	1323	SUNNY	f	f	f
95	317	5228	0.17	Hyderabad	2026-06-11 12:45:30.217949	1	9	261674.00	3829	SUNNY	f	f	f
96	1031	3575	0.17	Hyderabad	2026-06-11 12:45:30.217949	7	14	284120.00	3233	SUNNY	f	f	f
97	725	5771	0.05	Hyderabad	2026-06-11 12:45:30.217949	7	22	241818.00	4778	SUNNY	f	f	f
98	850	3414	0.02	Hyderabad	2026-06-11 12:45:30.217949	3	4	147883.00	4642	RAIN	f	f	f
99	542	6059	0.01	Hyderabad	2026-06-11 12:45:30.217949	4	6	330914.00	2222	SUNNY	f	f	f
100	785	771	0.16	Hyderabad	2026-06-11 12:45:30.217949	6	16	144325.00	5760	SUNNY	f	f	f
101	887	4109	0.11	Hyderabad	2026-06-11 12:45:30.217949	1	12	219184.00	1518	SUNNY	f	f	f
1	500	2200	0.08	Hyderabad	2026-06-11 11:49:27.797728	4	10	125000.00	2500	SUNNY	t	f	f
2	949	1335	0.13	Hyderabad	2026-06-11 12:45:30.217949	3	16	259374.00	3229	SUNNY	t	f	f
3	900	671	0.11	Hyderabad	2026-06-11 12:45:30.217949	5	23	437841.00	2849	RAIN	t	f	f
4	1024	1653	0.07	Hyderabad	2026-06-11 12:45:30.217949	2	21	175042.00	2300	SUNNY	t	f	f
5	289	1803	0.12	Hyderabad	2026-06-11 12:45:30.217949	1	20	365087.00	1129	SUNNY	t	f	f
\.


--
-- Data for Name: fraud_alert; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fraud_alert (id, description, fraud_type, resolved, severity, user_id) FROM stdin;
1	Same pickup/drop location repeated multiple times	FAKE_RIDE	f	HIGH	101
2	Same pickup/drop location repeated multiple times	FAKE_RIDE	f	HIGH	101
3	Same pickup/drop location repeated multiple times	FAKE_RIDE	f	HIGH	101
4	Duplicate payment or refund abuse detected	PAYMENT_FRAUD	f	CRITICAL	101
5	Same pickup/drop location repeated multiple times	FAKE_RIDE	f	HIGH	101
6	Duplicate payment or refund abuse detected	PAYMENT_FRAUD	f	CRITICAL	101
7	Same pickup/drop location repeated multiple times	FAKE_RIDE	f	HIGH	101
8	Duplicate payment or refund abuse detected	PAYMENT_FRAUD	f	CRITICAL	101
\.


--
-- Data for Name: international_analytics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.international_analytics (id, country_code, currency_code, region_code, total_revenue, total_rides, growth_percentage, analytics_date) FROM stdin;
1	IN	INR	KA	1250000.50	25000	18.50	2026-06-13 16:03:43.157
2	AE	AED	DXB	750000.00	12000	12.40	2026-06-13 16:03:43.157
3	EU	EUR	BERLIN	980000.75	17000	9.80	2026-06-13 16:03:43.157
\.


--
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices (id, country_code, currency_code, customer_name, fare_amount, ride_id, tax_amount, total_amount, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: model_audit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.model_audit (id, action, model_version, "timestamp") FROM stdin;
1	MODEL_RETRAINED	v2	2026-06-11 20:07:46.107987
2	MODEL_ACTIVATED	v1	2026-06-11 20:07:47.753437
\.


--
-- Data for Name: model_registry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.model_registry (id, model_name, model_version, algorithm, mae, rmse, r2, model_path, created_at, active) FROM stdin;
2	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 16:16:33.203983	f
3	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 16:46:55.434393	f
4	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 16:48:05.038773	f
5	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 16:48:40.897897	f
6	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 16:48:59.737805	f
7	DemandForecast	v2	RandomForest	0	0	0	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v2.model	2026-06-11 20:07:45.957867	f
1	DemandForecast	v1	RandomForest	1589.6794166666664	1806.1604920319776	5.078324460816731e-07	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v1.model	2026-06-11 15:24:51.234584	t
8	DemandForecast	v1	RandomForest	1589.6794166666664	1806.1604920319776	5.078324460816731e-07	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v1.model	2026-06-11 20:22:18.363863	f
9	DemandForecast	v1	RandomForest	1118.3791109022557	1435.1425888133558	0.12494504065464854	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v1.model	2026-06-11 22:00:21.624553	f
10	DemandForecast	v1	RandomForest	1118.3791109022557	1435.1425888133558	0.12494504065464854	C:\\Users\\NAGESH RIDER 46\\eclipse 123\\ml-service\\models\\demand-v1.model	2026-06-11 23:39:39.615455	f
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, message, recipient, retry_count, status, title, type, user_id) FROM stdin;
1	2026-05-15 11:17:18.379819	Your ride has started successfully	user@gmail.com	0	SENT	Ride Started	EMAIL	101
2	2026-05-15 11:31:40.649768	Your OTP is 4567	9876543210	0	SENT	Ride OTP	SMS	102
3	2026-05-15 11:32:20.290161	Your ride completed successfully	user@gmail.com	0	SENT	Ride Completed	EMAIL	103
4	2026-05-15 11:57:03.00897	Your OTP is 7890	9876543210	\N	SENT	OTP	SMS	102
5	2026-05-15 11:59:52.966627	Your OTP is 7890	9876543210	0	SENT	OTP	SMS	102
6	2026-05-18 13:42:24.1573	Protected API accessed using JWT	9876543210	0	SENT	Gateway JWT Test	SMS	101
7	2026-05-18 16:21:01.930661	Protected API accessed using JWT	9876543210	0	SENT	Gateway JWT Test	SMS	101
8	2026-05-19 13:42:28.944031	Protected API accessed using JWT	9876543210	1	SENT	Gateway JWT Test	SMS	101
\.


--
-- Data for Name: organizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizations (id, active, organization_code, organization_name, subscription_plan, tenant_id) FROM stdin;
1	t	ORG_A	Org A	ENTERPRISE	TENANT_001
2	t	ORG_B	Org B	STARTER	TENANT_002
3	t	TENANT_100	Rapido Chennai	STARTER	TENANT_100
\.


--
-- Data for Name: payment_gateway_config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_gateway_config (id, country_code, gateway_name, active) FROM stdin;
1	IN	RAZORPAY	t
2	AE	STRIPE	t
\.


--
-- Data for Name: prediction_metrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prediction_metrics (id, average_prediction, last_prediction_time, max_prediction, min_prediction, prediction_count) FROM stdin;
1	4116.407145833334	2026-06-11 21:49:32.396212	4118.224166666667	4103.688	8
\.


--
-- Data for Name: pricing_rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pricing_rules (id, tenant_id, base_fare, commission_percentage, surge_multiplier, city_adjustment, peak_surge_multiplier, tax_percentage, country_code, city_code, vehicle_type) FROM stdin;
1	TENANT_100	50.00	12	1.5	10.00	1.50	18.00	IN	BLR	BIKE
\.


--
-- Data for Name: regions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.regions (id, active, region_code, region_name, country_id, created_at, updated_at) FROM stdin;
1	t	KA	Karnataka	1	2026-06-13 14:54:39.129219	2026-06-13 14:54:39.129219
\.


--
-- Data for Name: ride_policies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ride_policies (id, tenant_id, active, base_fare, cancellation_fee, max_distance, ride_type) FROM stdin;
1	TENANT_100	t	30	10	25	BIKE
2	TENANT_100	t	100	25	100	CAB
\.


--
-- Data for Name: ride_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ride_status_history (id, message, ride_id, status, "timestamp") FROM stdin;
1	Ride has started	101	STARTED	2026-05-13 22:25:21.387468
2	Ride completed successfully	101	COMPLETED	2026-05-13 22:26:21.216684
\.


--
-- Data for Name: rides; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rides (id, completed_at, driver_id, drop_latitude, drop_longitude, estimated_distance, estimated_fare, pickup_latitude, pickup_longitude, requested_at, status, user_id, fare, tax, total_amount) FROM stdin;
1	\N	101	17.45	78.38	13.431042089433683	201.1725050732042	17.385	78.4867	2026-05-12 21:52:55.039676	CANCELLED	1	0.00	0.00	0.00
2	2026-06-04 16:15:33.917997	101	17.45	78.5	8.067703435585996	136.81244122703194	17.38	78.48	2026-06-04 16:13:03.462775	COMPLETED	1	0.00	0.00	0.00
3	\N	101	17.45	78.5	8.067703435585996	136.81244122703194	17.38	78.48	2026-06-04 16:30:35.967235	REQUESTED	1	0.00	0.00	0.00
4	\N	101	17.45	78.5	8.067703435585996	136.81244122703194	17.38	78.48	2026-06-04 16:50:41.994013	REQUESTED	1	0.00	0.00	0.00
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, tenant_id, role_name) FROM stdin;
1	TENANT_100	ADMIN
\.


--
-- Data for Name: service_zones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_zones (id, active, operating_hours, pricing_rule, supported_ride_types, zone_code, zone_name, city_id, created_at, updated_at) FROM stdin;
1	t	24x7	STANDARD	BIKE,AUTO,CAB	BLR-CENTRAL	Bangalore Central	1	2026-06-13 14:54:39.160879	2026-06-13 14:54:39.160879
\.


--
-- Data for Name: subscription_plans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscription_plans (id, tenant_id, analytics_access, driver_limit, ml_features, plan_name, ride_limit) FROM stdin;
1	SYSTEM	f	100	f	STARTER	1000
2	SYSTEM	t	1000	f	GROWTH	10000
3	SYSTEM	t	10000	t	ENTERPRISE	100000
\.


--
-- Data for Name: tax_rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tax_rules (id, country_code, percentage, tax_type, created_at, updated_at) FROM stdin;
1	IN	18.00	GST	2026-06-13 14:54:39.18821	2026-06-13 14:54:39.18821
2	AE	5.00	VAT	2026-06-13 14:54:39.18821	2026-06-13 14:54:39.18821
3	US	8.50	SALES_TAX	2026-06-13 14:54:39.18821	2026-06-13 14:54:39.18821
4	GB	20.00	VAT	2026-06-13 14:54:39.18821	2026-06-13 14:54:39.18821
5	CA	12.00	GST	2026-06-13 14:54:39.18821	2026-06-13 14:54:39.18821
\.


--
-- Data for Name: tenant_alerts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_alerts (id, tenant_id, alert_message, alert_type, severity, status) FROM stdin;
1	TENANT_100	Multiple failed logins detected	SECURITY_ALERT	HIGH	OPEN
2	TENANT_100	Multiple failed logins detected	SECURITY_ALERT	HIGH	OPEN
\.


--
-- Data for Name: tenant_audit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_audit (id, tenant_id, action_details, action_type, created_at, performed_by) FROM stdin;
1	TENANT_100	Enabled ML Forecast	FEATURE_CHANGE	2026-06-12 17:39:53.63942	admin
\.


--
-- Data for Name: tenant_billing; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_billing (id, tenant_id, monthly_charge, plan, feature_charge, total_charge, usage_charge) FROM stdin;
1	TENANT_100	9999	ENTERPRISE	1000	11499	500
\.


--
-- Data for Name: tenant_compliance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_compliance (id, tenant_id, compliance_status, compliance_type, remarks) FROM stdin;
1	TENANT_100	COMPLETED	KYC	KYC verification successful
\.


--
-- Data for Name: tenant_configuration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_configuration (id, tenant_id, commission_rule, pricing_rule, ride_category, notification_template) FROM stdin;
1	TENANT_100	15_PERCENT	SURGE_ENABLED	BIKE,AUTO,CAB	RIDE_BOOKED
\.


--
-- Data for Name: tenant_health; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_health (id, tenant_id, api_status, billing_status, database_status, notification_status) FROM stdin;
1	TENANT_100	UP	UP	UP	UP
\.


--
-- Data for Name: tenant_notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_notifications (id, tenant_id, message, notification_type, recipient, status) FROM stdin;
1	TENANT_100	Welcome to Rapido Chennai	EMAIL	admin@rapido.com	SENT
\.


--
-- Data for Name: tenant_sla; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_sla (id, tenant_id, sla_type, status, target_value) FROM stdin;
1	TENANT_100	AVAILABILITY	ACTIVE	99.99%
\.


--
-- Data for Name: tenants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenants (id, organization_id, status, tenant_code, tenant_id) FROM stdin;
1	3	ACTIVE	TENANT_100	TENANT_100
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, amount, created_at, driver_id, payer_id, ride_id, status, transaction_reference) FROM stdin;
1	250	2026-05-14 13:17:14.577539	101	1	501	REFUNDED	9c4b27e0-eb47-46dc-ad54-5fe7dc029540
\.


--
-- Data for Name: usage_tracking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usage_tracking (id, tenant_id, api_calls, drivers, rides, storage_usage_mb) FROM stdin;
1	TENANT_100	15000	500	10000	2048
\.


--
-- Data for Name: user_deletion_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_deletion_requests (id, user_id, status, created_at) FROM stdin;
1	100	COMPLETED	2026-06-13 10:27:34.07381
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rapido_user
--

COPY public.users (id, email, full_name, password, role, active, phone, profile_image, name, created_at, updated_at, phone_number, phone_number_e164) FROM stdin;
1	nagesh@gmail.com	Nagesh	$2a$10$HCZfPEtkJ1EUvQvlBXBw2eENwg95nRpx/SaZCkF0MzBv20hdxXShG	USER	\N	\N	\N	\N	\N	\N	\N	\N
2	nagesh2@gmail.com	\N	$2a$10$q8DTQPcsbSz5VoGpZRrdJ.p.vOE4boHkM3Rodyipy7gwa38MMQ0HO	USER	\N	\N	\N	\N	\N	\N	\N	\N
3	test@gmail.com	\N	$2a$10$rQQu1wpwr41yqG0I28gOa.OThLA9T4hVmBKjedRVQ1ZbEsZC52Kre	USER	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wallets (id, active, balance, user_id) FROM stdin;
1	t	1000	1
\.


--
-- Name: admin_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_users_id_seq', 1, true);


--
-- Name: admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admins_id_seq', 3, true);


--
-- Name: alerts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.alerts_id_seq', 1, true);


--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 4, true);


--
-- Name: branding_configuration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.branding_configuration_id_seq', 1, true);


--
-- Name: call_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.call_sessions_id_seq', 1, true);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_messages_id_seq', 12, true);


--
-- Name: cities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cities_id_seq', 1, true);


--
-- Name: compliance_configurations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compliance_configurations_id_seq', 3, true);


--
-- Name: consent_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consent_logs_id_seq', 2, true);


--
-- Name: countries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.countries_id_seq', 4, true);


--
-- Name: country_business_rules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.country_business_rules_id_seq', 6, true);


--
-- Name: currencies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currencies_id_seq', 7, true);


--
-- Name: driver_earnings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.driver_earnings_id_seq', 1, true);


--
-- Name: driver_location_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.driver_location_history_id_seq', 1, true);


--
-- Name: drivers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.drivers_id_seq', 3, true);


--
-- Name: exchange_rates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exchange_rates_id_seq', 6, true);


--
-- Name: feature_flags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feature_flags_id_seq', 5, true);


--
-- Name: feature_store_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feature_store_id_seq', 101, true);


--
-- Name: fraud_alert_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fraud_alert_id_seq', 8, true);


--
-- Name: international_analytics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.international_analytics_id_seq', 3, true);


--
-- Name: invoices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoices_id_seq', 1, false);


--
-- Name: model_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.model_audit_id_seq', 2, true);


--
-- Name: model_registry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.model_registry_id_seq', 10, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 8, true);


--
-- Name: organizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organizations_id_seq', 3, true);


--
-- Name: payment_gateway_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_gateway_config_id_seq', 2, true);


--
-- Name: prediction_metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prediction_metrics_id_seq', 1, true);


--
-- Name: pricing_rules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pricing_rules_id_seq', 1, true);


--
-- Name: regions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.regions_id_seq', 1, true);


--
-- Name: ride_policies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ride_policies_id_seq', 2, true);


--
-- Name: ride_status_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ride_status_history_id_seq', 2, true);


--
-- Name: rides_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rides_id_seq', 4, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, true);


--
-- Name: service_zones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_zones_id_seq', 1, true);


--
-- Name: subscription_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_plans_id_seq', 3, true);


--
-- Name: tax_rules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tax_rules_id_seq', 5, true);


--
-- Name: tenant_alerts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_alerts_id_seq', 2, true);


--
-- Name: tenant_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_audit_id_seq', 1, true);


--
-- Name: tenant_billing_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_billing_id_seq', 1, true);


--
-- Name: tenant_compliance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_compliance_id_seq', 1, true);


--
-- Name: tenant_configuration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_configuration_id_seq', 1, true);


--
-- Name: tenant_health_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_health_id_seq', 1, true);


--
-- Name: tenant_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_notifications_id_seq', 1, true);


--
-- Name: tenant_sla_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_sla_id_seq', 1, true);


--
-- Name: tenants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenants_id_seq', 1, true);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, true);


--
-- Name: usage_tracking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usage_tracking_id_seq', 1, true);


--
-- Name: user_deletion_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_deletion_requests_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rapido_user
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: wallets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wallets_id_seq', 1, true);


--
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: alerts alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: branding_configuration branding_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branding_configuration
    ADD CONSTRAINT branding_configuration_pkey PRIMARY KEY (id);


--
-- Name: call_sessions call_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_sessions
    ADD CONSTRAINT call_sessions_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: compliance_configurations compliance_configurations_country_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_configurations
    ADD CONSTRAINT compliance_configurations_country_code_key UNIQUE (country_code);


--
-- Name: compliance_configurations compliance_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_configurations
    ADD CONSTRAINT compliance_configurations_pkey PRIMARY KEY (id);


--
-- Name: consent_logs consent_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_logs
    ADD CONSTRAINT consent_logs_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: country_business_rules country_business_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country_business_rules
    ADD CONSTRAINT country_business_rules_pkey PRIMARY KEY (id);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: driver_earnings driver_earnings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_earnings
    ADD CONSTRAINT driver_earnings_pkey PRIMARY KEY (id);


--
-- Name: driver_location_history driver_location_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_location_history
    ADD CONSTRAINT driver_location_history_pkey PRIMARY KEY (id);


--
-- Name: driver_performance driver_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_performance
    ADD CONSTRAINT driver_performance_pkey PRIMARY KEY (driver_id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: exchange_rates exchange_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (id);


--
-- Name: feature_flags feature_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);


--
-- Name: feature_store feature_store_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feature_store
    ADD CONSTRAINT feature_store_pkey PRIMARY KEY (id);


--
-- Name: fraud_alert fraud_alert_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fraud_alert
    ADD CONSTRAINT fraud_alert_pkey PRIMARY KEY (id);


--
-- Name: international_analytics international_analytics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.international_analytics
    ADD CONSTRAINT international_analytics_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: model_audit model_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_audit
    ADD CONSTRAINT model_audit_pkey PRIMARY KEY (id);


--
-- Name: model_registry model_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_registry
    ADD CONSTRAINT model_registry_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: payment_gateway_config payment_gateway_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_gateway_config
    ADD CONSTRAINT payment_gateway_config_pkey PRIMARY KEY (id);


--
-- Name: prediction_metrics prediction_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prediction_metrics
    ADD CONSTRAINT prediction_metrics_pkey PRIMARY KEY (id);


--
-- Name: pricing_rules pricing_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pricing_rules
    ADD CONSTRAINT pricing_rules_pkey PRIMARY KEY (id);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: ride_policies ride_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_policies
    ADD CONSTRAINT ride_policies_pkey PRIMARY KEY (id);


--
-- Name: ride_status_history ride_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_status_history
    ADD CONSTRAINT ride_status_history_pkey PRIMARY KEY (id);


--
-- Name: rides rides_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT rides_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: service_zones service_zones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_zones
    ADD CONSTRAINT service_zones_pkey PRIMARY KEY (id);


--
-- Name: subscription_plans subscription_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);


--
-- Name: tax_rules tax_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_rules
    ADD CONSTRAINT tax_rules_pkey PRIMARY KEY (id);


--
-- Name: tenant_alerts tenant_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_alerts
    ADD CONSTRAINT tenant_alerts_pkey PRIMARY KEY (id);


--
-- Name: tenant_audit tenant_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_audit
    ADD CONSTRAINT tenant_audit_pkey PRIMARY KEY (id);


--
-- Name: tenant_billing tenant_billing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_billing
    ADD CONSTRAINT tenant_billing_pkey PRIMARY KEY (id);


--
-- Name: tenant_compliance tenant_compliance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_compliance
    ADD CONSTRAINT tenant_compliance_pkey PRIMARY KEY (id);


--
-- Name: tenant_configuration tenant_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_configuration
    ADD CONSTRAINT tenant_configuration_pkey PRIMARY KEY (id);


--
-- Name: tenant_health tenant_health_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_health
    ADD CONSTRAINT tenant_health_pkey PRIMARY KEY (id);


--
-- Name: tenant_notifications tenant_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_notifications
    ADD CONSTRAINT tenant_notifications_pkey PRIMARY KEY (id);


--
-- Name: tenant_sla tenant_sla_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_sla
    ADD CONSTRAINT tenant_sla_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: admins uk47bvqemyk6vlm0w7crc3opdd4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT uk47bvqemyk6vlm0w7crc3opdd4 UNIQUE (email);


--
-- Name: driver_earnings uk6xbbw9osq3dskemc6vl0uyi6i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_earnings
    ADD CONSTRAINT uk6xbbw9osq3dskemc6vl0uyi6i UNIQUE (driver_id);


--
-- Name: transactions uk94m9euoxupnom1p8mtwmk9q4g; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk94m9euoxupnom1p8mtwmk9q4g UNIQUE (transaction_reference);


--
-- Name: countries uk_country_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT uk_country_code UNIQUE (country_code);


--
-- Name: compliance_configurations uk_country_compliance; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_configurations
    ADD CONSTRAINT uk_country_compliance UNIQUE (country_code);


--
-- Name: tax_rules uk_country_tax_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_rules
    ADD CONSTRAINT uk_country_tax_type UNIQUE (country_code, tax_type);


--
-- Name: country_business_rules uk_country_vehicle; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country_business_rules
    ADD CONSTRAINT uk_country_vehicle UNIQUE (country_code, vehicle_type);


--
-- Name: currencies uk_currency_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT uk_currency_code UNIQUE (code);


--
-- Name: exchange_rates uk_exchange_rate; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT uk_exchange_rate UNIQUE (base_currency, target_currency, rate_date);


--
-- Name: feature_flags uk_feature_flag; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT uk_feature_flag UNIQUE (tenant_id, country_code, region_code, feature_name);


--
-- Name: service_zones ukiaa0s3gnfvn8998ggtne8fxqx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_zones
    ADD CONSTRAINT ukiaa0s3gnfvn8998ggtne8fxqx UNIQUE (zone_code);


--
-- Name: organizations uklj2ht6veutd7ylobki761jitv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT uklj2ht6veutd7ylobki761jitv UNIQUE (organization_code);


--
-- Name: cities ukmmxm1v9ejho8cyhd1xs01g0w8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT ukmmxm1v9ejho8cyhd1xs01g0w8 UNIQUE (city_code);


--
-- Name: regions ukr0e525uwp8x05ly7akgf4cvsx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT ukr0e525uwp8x05ly7akgf4cvsx UNIQUE (region_code);


--
-- Name: tenants ukr2h4deuvsyct6en1d7av037c7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT ukr2h4deuvsyct6en1d7av037c7 UNIQUE (tenant_code);


--
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- Name: usage_tracking usage_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usage_tracking
    ADD CONSTRAINT usage_tracking_pkey PRIMARY KEY (id);


--
-- Name: user_deletion_requests user_deletion_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_deletion_requests
    ADD CONSTRAINT user_deletion_requests_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: rapido_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rapido_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: idx1aq6y9dqmhf466hfhvrq2b3d2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx1aq6y9dqmhf466hfhvrq2b3d2 ON public.notifications USING btree (user_id);


--
-- Name: idx_analytics_country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_analytics_country ON public.international_analytics USING btree (country_code);


--
-- Name: idx_analytics_currency; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_analytics_currency ON public.international_analytics USING btree (currency_code);


--
-- Name: idx_audit_action; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit_action ON public.audit_log USING btree (action);


--
-- Name: idx_compliance_country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_compliance_country ON public.compliance_configurations USING btree (country_code);


--
-- Name: idx_country_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_country_active ON public.countries USING btree (active);


--
-- Name: idx_country_business_rule; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_country_business_rule ON public.country_business_rules USING btree (country_code);


--
-- Name: idx_country_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_country_code ON public.countries USING btree (country_code);


--
-- Name: idx_feature_tenant; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_feature_tenant ON public.feature_flags USING btree (tenant_id);


--
-- Name: idx_ride_chat; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ride_chat ON public.chat_messages USING btree (ride_id);


--
-- Name: idx_tax_country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tax_country ON public.tax_rules USING btree (country_code);


--
-- Name: idxaoi1m93ivnvcvfteq9poskfmg; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxaoi1m93ivnvcvfteq9poskfmg ON public.driver_location_history USING btree (driver_id);


--
-- Name: idxcyxiova5m63fegroy1pin5wvy; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxcyxiova5m63fegroy1pin5wvy ON public.notifications USING btree (type);


--
-- Name: idxg6c43jyo6y9w25dv9gy78ilga; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxg6c43jyo6y9w25dv9gy78ilga ON public.notifications USING btree (status);


--
-- Name: idxjg00hi1726irwg0s3vqa54vd1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxjg00hi1726irwg0s3vqa54vd1 ON public.transactions USING btree (payer_id);


--
-- Name: idxlih3nr7r2yxql2j9q158vthbg; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxlih3nr7r2yxql2j9q158vthbg ON public.transactions USING btree (ride_id);


--
-- Name: idxmkvc82cwstjeh3x9cquh7xjpi; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxmkvc82cwstjeh3x9cquh7xjpi ON public.transactions USING btree (status);


--
-- Name: idxsalwx8s6oisxfws8fbw2gpyct; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idxsalwx8s6oisxfws8fbw2gpyct ON public.driver_location_history USING btree (ride_id);


--
-- Name: regions fk2x36ly3wpe3l83kh32211kwf3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT fk2x36ly3wpe3l83kh32211kwf3 FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: cities fk312nt0rik1hqh54qg34l4nsk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT fk312nt0rik1hqh54qg34l4nsk3 FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: service_zones fkatfmpgrq7q01cfsg04x9grgi0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_zones
    ADD CONSTRAINT fkatfmpgrq7q01cfsg04x9grgi0 FOREIGN KEY (city_id) REFERENCES public.cities(id);


--
-- PostgreSQL database dump complete
--

\unrestrict L8lm4nyWRNiDKkbv9g0H77I6MgKTChufw4qUpOFcDgJtrGIc3WxVhegiTthZKbO

