apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-consumer

spec:

  replicas: 2

  selector:
    matchLabels:
      app: payment-consumer

  template:

    metadata:
      labels:
        app: payment-consumer

    spec:

      containers:

        - name: payment-consumer

          image: payment-consumer:latest

          env:

            - name: KAFKA_TOPIC
              value: payment-events

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092